version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every week
    schedule:
      interval: 'weekly'
    groups:
      minor-npm-dependencies:
        # Only group minor and patch updates (we want to carefully review major updates)
        update-types: [minor, patch]

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      minor-actions-dependencies:
        # Only group minor and patch updates (we want to carefully review major updates)
        update-types: [minor, patch]
